'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import SideBar from "@/components/sidebar";
import { Provider } from "react-redux";
import { store } from "@/components/store/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Provider store={store}>
      <html lang="en">
        <body className="{inter.className} bg-black">
            {children}
         </body>
      </html>
      </Provider>
    </ClerkProvider>
  );
}
